# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SFE_Dialog_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):

    def __init__(self, liquids):
        self.liquids = liquids

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(636, 599)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(12, 12, 621, 581))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.OKButton = QtWidgets.QPushButton(self.widget)
        self.OKButton.setObjectName("OKButton")
        self.gridLayout.addWidget(self.OKButton, 5, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 1, 1, 1, 1)
        self.RemoveButton = QtWidgets.QPushButton(self.widget)
        self.RemoveButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/arrow_left.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RemoveButton.setIcon(icon)
        self.RemoveButton.setObjectName("RemoveButton")
        self.gridLayout.addWidget(self.RemoveButton, 3, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 4, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 7, 1, 1, 1)
        self.CancelButton = QtWidgets.QPushButton(self.widget)
        self.CancelButton.setObjectName("CancelButton")
        self.gridLayout.addWidget(self.CancelButton, 6, 1, 1, 1)
        self.AddButton = QtWidgets.QPushButton(self.widget)
        self.AddButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/arrow_green.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AddButton.setIcon(icon1)
        self.AddButton.setObjectName("AddButton")
        self.gridLayout.addWidget(self.AddButton, 2, 1, 1, 1)
        self.allList = QtWidgets.QListWidget(self.widget)
        self.allList.setWordWrap(False)
        self.allList.setObjectName("allList")
        # item = QtWidgets.QListWidgetItem()
        # self.allList.addItem(item)
        # item = QtWidgets.QListWidgetItem()
        # self.allList.addItem(item)
        # item = QtWidgets.QListWidgetItem()
        # self.allList.addItem(item)
        # item = QtWidgets.QListWidgetItem()
        # self.allList.addItem(item)
        # item = QtWidgets.QListWidgetItem()
        # self.allList.addItem(item)
        self.gridLayout.addWidget(self.allList, 0, 0, 8, 1)
        self.myList = QtWidgets.QListWidget(self.widget)
        self.myList.setObjectName("myList")
        self.gridLayout.addWidget(self.myList, 0, 2, 8, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.AddButton.clicked.connect(self.add_button)
        self.RemoveButton.clicked.connect(self.remove_button)
        self.OKButton.clicked.connect(Dialog.accept)
        self.CancelButton.clicked.connect(Dialog.reject)
        self.allList.itemDoubleClicked.connect(self.move_to_mylist)
        self.myList.itemDoubleClicked.connect(self.move_to_alllist)

    def add_button(self):
        if self.allList.currentRow() != -1:
            self.move_to_mylist()
        else:
            self.allList.setCurrentRow(0)
            self.move_to_mylist()

    def remove_button(self):
        if self.myList.currentRow() != -1:
            self.move_to_alllist()
        else:
            self.myList.setCurrentRow(0)
            self.move_to_alllist()

    def move_to_alllist(self):
        row = self.myList.currentRow()
        self.item = self.myList.takeItem(row)
        self.allList.addItem(self.item)

    def move_to_mylist(self):
        row = self.allList.currentRow()
        self.item = self.allList.takeItem(row)
        self.myList.addItem(self.item)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Select Liquid"))
        self.OKButton.setText(_translate("Dialog", "OK"))
        self.CancelButton.setText(_translate("Dialog", "Cancel"))
        __sortingEnabled = self.allList.isSortingEnabled()
        self.allList.setSortingEnabled(False)
        for index, value in enumerate(self.liquids):
            _ = QtWidgets.QListWidgetItem()
            _.setText(value)
            self.allList.addItem(_)

        # item = self.allList.item(1)
        # item.setText(_translate("Dialog", "Liquid_1"))
        # item = self.allList.item(2)
        # item.setText(_translate("Dialog", "Liquid_2"))
        # item = self.allList.item(3)
        # item.setText(_translate("Dialog", "Liquid_3"))
        # item = self.allList.item(4)
        # item.setText(_translate("Dialog", "Liquid_4"))
        self.allList.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys

    result = ['water', 'water2', 'water3']
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog(result)
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
