# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaces/setting_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(747, 447)
        Form.setStyleSheet("QWidget{\n"
                           "    background-color: rgb(80, 80, 80);\n"
                           "}\n"
                           "QLabel{\n"
                           "    color:  rgb(250, 120, 255);\n"
                           "    background-color: grey;\n"
                           "    border-radius: 10px;\n"
                           "    font: bold, 14px\n"
                           "}\n"
                           "QPushButton {\n"
                           "    color: rgb(250, 120, 255);\n"
                           "    background-color: grey;\n"
                           "    border-style: outset;\n"
                           "    border-width: 3px;\n"
                           "    border-radius: 15px;\n"
                           "    border-color: rgb(255,120,200);\n"
                           "    font: bold 14px;\n"
                           "    min-width: 140px;\n"
                           "    padding: 6px;\n"
                           "}\n"
                           "QLineEdit{\n"
                           "    color: white;\n"
                           "    border-radius: 15px;\n"
                           "    border-width: 2px;\n"
                           "    border-style: outset;\n"
                           "    border-radius: 25px;\n"
                           "    border-color: rgb(255,255,255);\n"
                           "}\n"
                           "QTableWidget{\n"
                           "    color: rgb(250, 120, 255);\n"
                           "    background-color: grey;\n"
                           "}")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.tableWidget, 0, 1, 4, 1)
        self.addliquidButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addliquidButton.sizePolicy().hasHeightForWidth())
        self.addliquidButton.setSizePolicy(sizePolicy)
        self.addliquidButton.setStyleSheet("")
        self.addliquidButton.setObjectName("addliquidButton")
        self.gridLayout.addWidget(self.addliquidButton, 0, 0, 1, 1)
        self.calculateButton = QtWidgets.QPushButton(Form)
        self.calculateButton.setObjectName("calculateButton")
        self.gridLayout.addWidget(self.calculateButton, 3, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 357, 339))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 2, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.tableWidget.setSortingEnabled(True)
        self.addliquidButton.setText(_translate("Form", "Add Liquids"))
        self.calculateButton.setText(_translate("Form", "Calculate"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
