# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow_v2.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1045, 528)
        MainWindow.setStyleSheet("QFrame{\n"
"    background-color: rgb(120, 120, 120);\n"
"    border-radius: 25px;\n"
"}\n"
"QMainWindow{\n"
"    background-color:rgb(255,255,255)\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 10, 1009, 482))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ButtonsFrame = QtWidgets.QFrame(self.layoutWidget)
        self.ButtonsFrame.setMinimumSize(QtCore.QSize(140, 480))
        self.ButtonsFrame.setMaximumSize(QtCore.QSize(200, 16377))
        self.ButtonsFrame.setStyleSheet("QPushButton {\n"
"    color: rgb(250, 120, 255);\n"
"    background-color: grey;\n"
"    border-style: outset;\n"
"    border-width: 3px;\n"
"    border-radius: 25px;\n"
"    border-color: rgb(255,120,200);\n"
"    font: bold 14px;\n"
"    min-width: 140px;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:checked {\n"
"    background-color: rgb(80, 80, 80);\n"
"    border-style: inset;\n"
"}\n"
"QFrame{\n"
"    background-color: rgb(120, 120, 120);\n"
"    border-radius: 25px;\n"
"}\n"
"")
        self.ButtonsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ButtonsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ButtonsFrame.setObjectName("ButtonsFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.ButtonsFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.settingsButton = QtWidgets.QPushButton(self.ButtonsFrame)
        self.settingsButton.setMinimumSize(QtCore.QSize(158, 120))
        self.settingsButton.setStyleSheet("")
        self.settingsButton.setCheckable(True)
        self.settingsButton.setAutoExclusive(True)
        self.settingsButton.setDefault(False)
        self.settingsButton.setObjectName("settingsButton")
        self.gridLayout.addWidget(self.settingsButton, 1, 0, 1, 1)
        self.theoryButton = QtWidgets.QPushButton(self.ButtonsFrame)
        self.theoryButton.setMinimumSize(QtCore.QSize(158, 120))
        self.theoryButton.setStyleSheet("")
        self.theoryButton.setCheckable(True)
        self.theoryButton.setChecked(True)
        self.theoryButton.setAutoExclusive(True)
        self.theoryButton.setAutoDefault(False)
        self.theoryButton.setDefault(False)
        self.theoryButton.setFlat(False)
        self.theoryButton.setObjectName("theoryButton")
        self.gridLayout.addWidget(self.theoryButton, 0, 0, 1, 1)
        self.measurmentButton = QtWidgets.QPushButton(self.ButtonsFrame)
        self.measurmentButton.setMinimumSize(QtCore.QSize(158, 120))
        self.measurmentButton.setSizeIncrement(QtCore.QSize(100, 0))
        self.measurmentButton.setStyleSheet("")
        self.measurmentButton.setCheckable(True)
        self.measurmentButton.setAutoExclusive(True)
        self.measurmentButton.setObjectName("measurmentButton")
        self.gridLayout.addWidget(self.measurmentButton, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.ButtonsFrame, 0, 0, 1, 1)
        self.MainFrame = QtWidgets.QFrame(self.layoutWidget)
        self.MainFrame.setMinimumSize(QtCore.QSize(700, 480))
        self.MainFrame.setToolTipDuration(1)
        self.MainFrame.setStyleSheet("QFrame{\n"
"    backgroundcolor: rgb(255, 255, 0)}")
        self.MainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainFrame.setObjectName("MainFrame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.MainFrame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame = QtWidgets.QFrame(self.MainFrame)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.theoryCombobox = QtWidgets.QComboBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.theoryCombobox.sizePolicy().hasHeightForWidth())
        self.theoryCombobox.setSizePolicy(sizePolicy)
        self.theoryCombobox.setMinimumSize(QtCore.QSize(606, 30))
        self.theoryCombobox.setAutoFillBackground(False)
        self.theoryCombobox.setStyleSheet("QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"    padding: 5px 2px 5px 2px;\n"
"    min-width: 600px;\n"
"}\n"
"QComboBox::drop-down {\n"
"    border: 0px;\n"
"}\n"
"QFrame{\n"
"background-color: rgb(255,255,255);\n"
"border-radius: 2px;\n"
"\n"
"}\n"
"\n"
"")
        self.theoryCombobox.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.theoryCombobox.setObjectName("theoryCombobox")
        self.theoryCombobox.addItem("")
        self.theoryCombobox.addItem("")
        self.theoryCombobox.addItem("")
        self.gridLayout_4.addWidget(self.theoryCombobox, 0, 1, 1, 1)
        self.ctywLabel = QtWidgets.QLabel(self.frame)
        self.ctywLabel.setStyleSheet("QLabel{\n"
"    color:rgb(250, 120, 255);\n"
"    background-color: rgb(80, 80, 80);\n"
"    border-radius: 10px;\n"
"}")
        self.ctywLabel.setScaledContents(True)
        self.ctywLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ctywLabel.setObjectName("ctywLabel")
        self.gridLayout_4.addWidget(self.ctywLabel, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_4.addWidget(self.frame_2, 1, 0, 1, 2)
        self.gridLayout_4.setColumnStretch(0, 4)
        self.gridLayout_4.setColumnStretch(1, 7)
        self.gridLayout_4.setRowStretch(0, 1)
        self.gridLayout_4.setRowStretch(1, 10)
        self.gridLayout_3.addWidget(self.frame, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.MainFrame, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1045, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.settingsButton.setText(_translate("MainWindow", "SETTINGS"))
        self.theoryButton.setText(_translate("MainWindow", "READ THEORY "))
        self.measurmentButton.setText(_translate("MainWindow", "MEASURMENT"))
        self.theoryCombobox.setItemText(0, _translate("MainWindow", "Van-Oss"))
        self.theoryCombobox.setItemText(1, _translate("MainWindow", "Zeisman"))
        self.theoryCombobox.setItemText(2, _translate("MainWindow", "Groompler"))
        self.ctywLabel.setText(_translate("MainWindow", "Choose Theory You Want"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
